no.59 task
jijiechen/dotnetclub pull request #62
Opened 2019-10-10 01:13 UTC by madeinchinalmc

no.59 task pull request

2019-10-10 02:21 UTC, ElderJames commented
commit message应该是修改的功能并关联的issue

2019-10-28 13:50 UTC, jijiechen requested changes
多谢提交 PR。但仍有多处需要修改完善的地方，请查看。
如有不明确的，请跟贴讨论。

2019-10-28 13:50 UTC, jijiechen commented on src/Discussion.Web/Views/Topic/List.cshtml
> +<<<<<<< HEAD
这个是合并标记，请去掉。

2019-10-28 13:50 UTC, jijiechen commented on src/Discussion.Web/Views/Topic/List.cshtml
> +=======
这个是合并标记，请去掉。

2019-10-28 13:50 UTC, jijiechen commented on src/Discussion.Web/Views/Topic/List.cshtml
> +>>>>>>> origin/master
这个是合并标记，请去掉。

2019-10-28 13:50 UTC, jijiechen commented on src/Discussion.Web/Discussion.Web.csproj
> +    <Folder Include=".aspnet\DataProtection-Keys\" />
这个是源代码所不必要的。请去掉。

2019-10-28 13:50 UTC, jijiechen commented on src/Discussion.Web/Discussion.Web.csproj
> +    <Folder Include="wwwroot\dist\" />
这个是源代码所不必要的。请去掉。

2019-10-28 13:50 UTC, jijiechen commented on src/Discussion.Web/Views/Topic/List.cshtml
> +                    if (user.VerifiedPhoneNumber == null || string.IsNullOrWhiteSpace(user.VerifiedPhoneNumber.PhoneNumber))
这里的判断逻辑是错误的。应该配合使用 SiteSettings 里面的 RequireUserPhoneNumberVerified 来判断。

2019-10-28 13:50 UTC, jijiechen commented on src/Discussion.Web/appsettings.json
> +  "pgsqlConnectionString": "Data Source=dotnetclub-lx5p4q-temp.db",
这只是一个示例配置文件，所以请不要修改它的值。如果要在本地运行，请在本地创建 appsettings.Development.json 文件即可。

2019-10-28 13:50 UTC, jijiechen commented on src/Discussion.Web/wwwroot/scripts/markdown-editor.js
> +>>>>>>> origin/master
请去除多余的合并标记。

2019-10-28 13:50 UTC, jijiechen commented on test/Discussion.Admin.Tests/Properties/launchSettings.json
> +{
这个也是没必要的，请去除。

2019-10-28 13:50 UTC, jijiechen commented on test/Discussion.Web.Tests/Properties/launchSettings.json
> +{
这个也是没必要的，请去除。

2019-12-25 09:07 UTC, closed without merging